### ISSUE TITLE
How can i add support for other dictionary keys

### ISSUE THREAD

**Issue by Uskompuf** [thatguywiththatname/PCPartPicker-API#3]
I was wondering how i can add extra dictionary keys for products such as socket for motherboards etc.

Thanks

**Comment by thatguywiththatname** [comment]
If you take a look at [_productsData.py](https://github.com/thatguywiththatname/PCPartPicker-API/blob/master/PCPartPicker_API/_productsData.py), the motherboard category already supports socket information, as well as other keys

**Comment by Uskompuf** [comment]
Sorry my bad on the socket, was also wondering on the possibility of adding other keys such as max ram speed, are the one's already implemented the only ones possible? If their is a process to add extra keys i could try. 

![image](https://user-images.githubusercontent.com/22492406/49793042-4d5b2a80-fd88-11e8-9266-dc8e5f388bfd.png)

I had a look at the code but not sure how you find the correct key names?

Thanks

**Comment by thatguywiththatname** [comment]
I see. So this API works specifically by scraping the product lists, for example, [this](https://pcpartpicker.com/products/motherboard/). As you're aware that page doesn't contain the extra info you want.

What you want is it to look at the individual product pages. To do this a lot of code would need to be re-written, and it would include making 100+ requests instead of ~5 (assuming there are an average of 5 pages for any given product).

Doing this would increase the time taken for an API request from several seconds into minutes, if not tens of minutes.

This is something you could figure out and implement yourself, in a fork or your own script(s), but not something I would be happy implementing into this API.

**Comment by thatguywiththatname** [comment]
If you want to write this yourself I would suggest checking out HTML parsing libraries such as [BeautifulSoup4](https://pypi.org/project/beautifulsoup4/) and [requests-html](https://github.com/kennethreitz/requests-html), as that is how you would extract the data from the webppage.

**Comment by Uskompuf** [comment]
Thanks for the great detailed reply. Would it be hard to add image URL of product as it is on the main page or is it difficult due to it not being shown?

I will have a look at those libraries regarding the other statistics.

Thanks

**Comment by thatguywiththatname** [comment]
Since the images aren't on the list page but the actual product page, it is the same problem.

Sorry I couldn't be of more help!

**Comment by Uskompuf** [comment]
Sorry i was looking on mobile where the images are displayed

**Comment by thatguywiththatname** [comment]
It might actually be possible to pull images from the mobile version of the site, I'll have to look into it

**Comment by Uskompuf** [comment]
Any luck with pulling from the mobile version? One thing to not is that the thumbnail images are in 240p but if you change the end of the url from 240p to 1600 you can get much higher resolution images. Also just wanted to say thanks for how great your library is I've just managed to combine cpu's from your library with cpu benchmarks.
![image](https://user-images.githubusercontent.com/22492406/50036815-027b3480-0060-11e9-8a5a-c2e7b342c608.png)
I have the id for each cpu and am hyperlinking to the pcpartpicker page, do you have any further suggestions to scrape each individual item if i have their id.

Thanks

**Comment by Uskompuf** [comment]
I also just noticed that the list view on PCPP includes images as well.

**Comment by thatguywiththatname** [comment]
Sorry for the week late reply!

To get the image URLs the request has to be made with a user agent from a mobile device.

I haven't looked into the details yet, but if you want to implement it yourself, start there.

**Comment by Uskompuf** [comment]
Hey I went along the route of scraping each individual product so I could also get socket and image
