### ISSUE TITLE
Can you add capability to scrape data using particular URL with including a filter (eg:- #k=30)

### ISSUE THREAD

**Issue by SLRoar** [thatguywiththatname/PCPartPicker-API#4]
It is more helpful if we could be able to scrape by adding a filter.

https://pcpartpicker.com/products/cpu/#k=30

then we can scrape data by adding a filter to a product. I think it can be done by adding a method to scrape data by a URL with filters it is more useful to us. 

Thank You

**Comment by thatguywiththatname** [comment]
Thanks for the suggestion

Yes I will implement this into the package

**Comment by SLRoar** [comment]
Thanks for fast reply and appreciate your work

**Comment by thatguywiththatname** [comment]
Implemented your request in [this commit](https://github.com/thatguywiththatname/PCPartPicker-API/commit/f0006f290e5c01913ae05d21f403dfc8af0eb4d6)

I have updated the code on Git and the package on PyPi

I have also updated the documentation, hopefully its easy to understand

Thanks again for the suggestion, I hope you find the package useful 😃

**Comment by SLRoar** [comment]
Ok, @thatguywiththatname I will let You know if there any issue with that.

Thank You
